#!/bin/bash
hostname=`hostname -I`
echo
echo Total Number  of TCP Connections :: `netstat -anp | grep $hostname | grep java | awk '{print $5,$6}' | sed 's/:.* / /' | sort | uniq -c | awk '{sum+=$1} END{ print sum}'`
echo
echo "#######" Total Count of the Client TCP Connections "######"
netstat -anp | grep $hostname | grep java | awk '{print $5,$6}' | sed 's/:.* / /' | sort | uniq -c > /tmp/total_tcp_connections
cat /tmp/total_tcp_connections  |  sed "s/^[ \t]*//" | awk 'BEGIN{print "Count ForeignAddress State"}1'| sed 's/ /,|,/g' | column -s ',' -t
echo
##awk 'BEGIN{print "Count ForeignAddress State"}1' /tmp/total_tcp_connections

